# Numpy Challenge

In [75]:
import numpy as np

In [76]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [97]:
# finds distinct values of the array
values = np.unique(arr)
values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
# Computes row-wise counts of all distinct values in the array
count = np.zeros((6,10), dtype=int)
for j in range(6):
    for i in values:
        count[j,i-1] = np.count_nonzero(arr[j,:]==i) # Counts the number of non-zero values in the array

In [96]:
count

array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

# Pandas Challenge

In [82]:
import pandas as pd

In [107]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

In [108]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Max.Price'], dtype='object')

In [126]:
df[['Manufacturer','Model','Type']] = df[['Manufacturer','Model','Type']].fillna('missing')

In [141]:
df.set_index(['Manufacturer', 'Model','Type'])

Min.Price  Max.Price
Manufacturer Model         Type                         
Acura        Integra       Small         12.9       18.8
missing      Legend        Midsize       29.2       38.7
Audi         90            Compact       25.9       32.3
             100           Midsize        NaN       44.6
BMW          535i          Midsize        NaN        NaN
Buick        Century       Midsize       14.2       17.3
             LeSabre       Large         19.9        NaN
             Roadmaster    Large         22.6       24.9
             Riviera       Midsize       26.3       26.3
Cadillac     DeVille       Large         33.0       36.3
             Seville       Midsize       37.5       42.7
Chevrolet    Cavalier      Compact        8.5       18.3
             Corsica       Compact       11.4       11.4
             Camaro        Sporty        13.4       16.8
             Lumina        Midsize       13.4       18.4
             Lumina_APV    Van           14.7       18.0
             Astro         Van           14.7       18.6
             Caprice       Large         18.0       19.6
             Corvette      Sporty        34.6       41.5
missing      Concorde      Large         18.4       18.4
Chrysler     LeBaron       Compact       14.5       17.1
             Imperial      Large         29.5       29.5
Dodge        Colt          Small          7.9       10.6
             Shadow        Small          8.4       14.2
             Spirit        Compact       11.9       14.7
             Caravan       Van            NaN       24.4
             Dynasty       Midsize       14.8       16.4
             Stealth       Sporty        18.5       33.1
Eagle        Summit        Small          7.9       16.5
             Vision        Large          NaN       21.2
...                                       ...        ...
Nissan       Sentra        Small          8.7       14.9
             Altima        Compact       13.0       18.3
             Quest         Van           16.7       21.5
             Maxima        Midsize       21.0       22.0
Oldsmobile   Achieva       Compact       13.0       14.0
             Cutlass_Ciera Midsize       14.2       18.4
             Silhouette    Van           19.5       19.5
             Eighty-Eight  Large         19.5       21.9
Plymouth     Laser         Sporty        11.4       17.4
Pontiac      LeMans        Small          NaN        9.9
             Sunbird       Compact        9.4       12.8
             Firebird      missing       14.0       21.4
             Grand_Prix    Midsize       15.4       21.6
             Bonneville    Large         19.4       29.4
Saab         900           Compact       20.3       37.1
Saturn       SL            Small          9.2       12.9
Subaru       Justy         Small          7.3        9.5
             Loyale        Small         10.5       11.3
             Legacy        Compact       16.3       22.7
Suzuki       Swift         missing        7.3        NaN
Toyota       Tercel        Small          NaN       11.8
             Celica        Sporty        14.2       22.6
             Camry         Midsize       15.2       21.2
             Previa        Van            NaN       26.6
Volkswagen   Fox           Small          8.7        9.5
             Eurovan       Van           16.6       22.7
             Passat        Compact       17.6       22.4
             Corrado       Sporty        22.9       23.7
Volvo        240           Compact       21.8       23.5
missing      850           Midsize       24.8       28.5

[93 rows x 2 columns]

In [124]:
df.index.is_unique

True

Index created using columns Manufacturer, Model and Type is unique and is a primary key

In [142]:
# brute-force check
index_key = df['Manufacturer']+ '_' + df['Model'] + '_' + df['Type']

In [143]:
index_key.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...  
63    False
64    False
65    False
66    False
67    False
68    False
69    False
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79    False
80    False
81    False
82    False
83    False
84    False
85    False
86    False
87    False
88    False
89    False
90    False
91    False
92    False
Length: 93, dtype: bool

In [146]:
index_key

0                  Acura_Integra_Small
1               missing_Legend_Midsize
2                      Audi_90_Compact
3                     Audi_100_Midsize
4                     BMW_535i_Midsize
5                Buick_Century_Midsize
6                  Buick_LeSabre_Large
7               Buick_Roadmaster_Large
8                Buick_Riviera_Midsize
9               Cadillac_DeVille_Large
10            Cadillac_Seville_Midsize
11          Chevrolet_Cavalier_Compact
12           Chevrolet_Corsica_Compact
13             Chevrolet_Camaro_Sporty
14            Chevrolet_Lumina_Midsize
15            Chevrolet_Lumina_APV_Van
16                 Chevrolet_Astro_Van
17             Chevrolet_Caprice_Large
18           Chevrolet_Corvette_Sporty
19              missing_Concorde_Large
20            Chrysler_LeBaron_Compact
21             Chrysler_Imperial_Large
22                    Dodge_Colt_Small
23                  Dodge_Shadow_Small
24                Dodge_Spirit_Compact
25                   Dodg